const WATCHES_PRODUCTS = [
    // ── AUDEMARS PIGUET ───────────────────────────────────────────────────────

    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Frosted Black", referencia: "26240ST.OO.1320ST.02", medida: "41mm", material: "Acero Inoxidable", caratula: "Negra Esmerilada", movimiento: "Automático (Cal. 2385)", precio: 10185, imagen: "relojes/AP_Royal_Oak_Chrono_Frosted_Black_Diagonal_26.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Frosted Gold", referencia: "26240BA.GG.1320BA.01", medida: "41mm", material: "Oro Amarillo 18k", caratula: "Dorada Esmerilada", movimiento: "Automático (Cal. 2385)", precio: 9985, imagen: "relojes/AP_Royal_Oak_Chrono_Frosted_Gold_Diagonal_27.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Frosted Silver", referencia: "26240PT.OO.1220PT.01", medida: "41mm", material: "Platino", caratula: "Gris Esmerilada", movimiento: "Automático (Cal. 2385)", precio: 10185, imagen: "relojes/AP_Royal_Oak_Chrono_Frosted_Silver_Diagonal_25.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Gold White Dial", referencia: "26240BA.OO.1320BA.02", medida: "41mm", material: "Oro Amarillo 18k", caratula: "Blanca", movimiento: "Automático (Cal. 2385)", precio: 10010, imagen: "relojes/AP_Royal_Oak_Chrono_Gold_White_Dial_Diagonal_79.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Rose Gold", referencia: "26331OR.OO.1220OR.02", medida: "41mm", material: "Oro Rosa 18k", caratula: "Salmón", movimiento: "Automático (Cal. 2385)", precio: 10150, imagen: "relojes/AP_Royal_Oak_Chrono_Rose_Gold_Diagonal_59.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Steel Black", referencia: "26331ST.OO.1220ST.02", medida: "41mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático (Cal. 2385)", precio: 10110, imagen: "relojes/AP_Royal_Oak_Chrono_Steel_Black_Diagonal_77.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Chronograph Yellow Gold", referencia: "26331BA.OO.1220BA.01", medida: "41mm", material: "Oro Amarillo 18k", caratula: "Plateada", movimiento: "Automático (Cal. 2385)", precio: 10190, imagen: "relojes/AP_Royal_Oak_Chrono_Yellow_Gold_Diagonal_67.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Rose Gold Black Dial", referencia: "15500OR.OO.1220OR.01", medida: "41mm", material: "Oro Rosa 18k", caratula: "Negra", movimiento: "Automático (Cal. 4302)", precio: 10070, imagen: "relojes/AP_Royal_Oak_Rose_Gold_Black_Dial_Diagonal_61.jpeg", galeria: [], status: "Disponible" },
    { marca: "Audemars Piguet", modelo: "Royal Oak Steel Silver Dial", referencia: "15500ST.OO.1220ST.04", medida: "41mm", material: "Acero Inoxidable", caratula: "Plateada", movimiento: "Automático (Cal. 4302)", precio: 10135, imagen: "relojes/AP_Royal_Oak_Steel_Silver_Dial_Diagonal_68.jpeg", galeria: [], status: "Disponible" },

    // ── BULGARI ───────────────────────────────────────────────────────────────
    { marca: "Bulgari", modelo: "Octo Finissimo Ultra Black", referencia: "103426", medida: "40mm", material: "Titanio DLC Negra", caratula: "Negra Esqueleto", movimiento: "Automático (Cal. BVL 138)", precio: 10060, imagen: "relojes/Bulgari_Octo_Finissimo_Black_Diagonal_52.jpeg", galeria: [], status: "Disponible" },

    // ── CARTIER ───────────────────────────────────────────────────────────────
    { marca: "Cartier", modelo: "Ballon Bleu Correa Piel", referencia: "W2BB0022", medida: "42mm", material: "Acero Inoxidable", caratula: "Plateada", movimiento: "Automático (Cal. 1847 MC)", precio: 10125, imagen: "relojes/Cartier_Ballon_Bleu_Leather_Diagonal_76.jpeg", galeria: [], status: "Disponible" },
    { marca: "Cartier", modelo: "Ballon Bleu Steel", referencia: "WSBB0061", medida: "42mm", material: "Acero Inoxidable", caratula: "Plateada", movimiento: "Automático (Cal. 1847 MC)", precio: 10030,
      imagen: "relojes/Cartier_Ballon_Bleu_Steel_Diagonal_2357.jpg",
      galeria: ["relojes/Cartier_Ballon_Bleu_Steel_Diagonal_2357 (1).jpg","relojes/Cartier_Ballon_Bleu_Steel_Diagonal_2357 (2).jpg","relojes/Cartier_Ballon_Bleu_Steel_Diagonal_2357 (3).jpg","relojes/Cartier_Ballon_Bleu_Steel_Diagonal_2357 (4).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Roadster Steel Black", referencia: "W62041V3", medida: "40mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático (Cal. 8510 MC)", precio: 10045, imagen: "relojes/Cartier_Roadster_Steel_Black_Dial_Diagonal_37.jpeg", galeria: [], status: "Disponible" },

    { marca: "Cartier", modelo: "Santos Steel White Dial", referencia: "WSSA0029", medida: "39.8mm", material: "Acero Inoxidable", caratula: "Blanca",  movimiento: "Automático (Cal. 1847 MC)", precio: 10000,
      imagen: "relojes/Cartier_Santos_Steel_White_Dial_Diagonal_2023.jpg",
      galeria: ["relojes/Cartier_Santos_Steel_White_Dial_Diagonal_2023 (1).jpg","relojes/Cartier_Santos_Steel_White_Dial_Diagonal_2023 (2).jpg","relojes/Cartier_Santos_Steel_White_Dial_Diagonal_2023 (3).jpg","relojes/Cartier_Santos_Steel_White_Dial_Diagonal_2023 (4).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos ADLC Black Bezel", referencia: "WSSA0048", medida: "39.8mm", material: "Acero Inoxidable y ADLC", caratula: "Negra", movimiento: "Automático (Cal. 1847 MC)", precio: 9985,
      imagen: "relojes/Cartier_Santos_ADLC_Black_Bezel_Diagonal_2034.jpg",
      galeria: ["relojes/Cartier_Santos_ADLC_Black_Bezel_Diagonal_2034 (1).jpg","relojes/Cartier_Santos_ADLC_Black_Bezel_Diagonal_2034 (2).jpg","relojes/Cartier_Santos_ADLC_Black_Bezel_Diagonal_2034 (3).jpg","relojes/Cartier_Santos_ADLC_Black_Bezel_Diagonal_2034 (4).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Gold White Dial", referencia: "WGSA0030", medida: "39.8mm", material: "Oro Amarillo 18k", caratula: "Blanca", movimiento: "Automático (Cal. 1847 MC)", precio: 10010,
      imagen: "relojes/Cartier_Santos_Gold_White_Dial_Diagonal_2038.jpg",
      galeria: ["relojes/Cartier_Santos_Gold_White_Dial_Diagonal_2038 (1).jpg","relojes/Cartier_Santos_Gold_White_Dial_Diagonal_2038 (2).jpg","relojes/Cartier_Santos_Gold_White_Dial_Diagonal_2038 (3).jpg","relojes/Cartier_Santos_Gold_White_Dial_Diagonal_2038 (4).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Steel Blue Dial", referencia: "WSSA0030", medida: "39.8mm", material: "Acero Inoxidable", caratula: "Azul", movimiento: "Automático (Cal. 1847 MC)", precio: 10105,
      imagen: "relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2042.jpg",
      galeria: ["relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2042 (1).jpg","relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2042 (2).jpg","relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2042 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Two-Tone White Dial", referencia: "W2SA0011", medida: "39.8mm", material: "Acero y Oro (Two-Tone)", caratula: "Blanca", movimiento: "Automático (Cal. 1847 MC)", precio: 10110,
      imagen: "relojes/Cartier_Santos_Two-Tone_White_Dial_Diagonal_2045.jpg",
      galeria: ["relojes/Cartier_Santos_Two-Tone_White_Dial_Diagonal_2045 (1).jpg","relojes/Cartier_Santos_Two-Tone_White_Dial_Diagonal_2045 (2).jpg","relojes/Cartier_Santos_Two-Tone_White_Dial_Diagonal_2045 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Steel Green Dial", referencia: "WSSA0061", medida: "39.8mm", material: "Acero Inoxidable", caratula: "Verde", movimiento: "Automático (Cal. 1847 MC)", precio: 10175,
      imagen: "relojes/Cartier_Santos_Steel_Green_Dial_Diagonal_2050.jpg",
      galeria: ["relojes/Cartier_Santos_Steel_Green_Dial_Diagonal_2050 (1).jpg","relojes/Cartier_Santos_Steel_Green_Dial_Diagonal_2050 (2).jpg","relojes/Cartier_Santos_Steel_Green_Dial_Diagonal_2050 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Steel Blue Dial II", referencia: "WSSA0062", medida: "39.8mm", material: "Acero Inoxidable", caratula: "Azul Marino", movimiento: "Automático (Cal. 1847 MC)", precio: 10020,
      imagen: "relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2314.jpg",
      galeria: ["relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2314 (1).jpg","relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2314 (2).jpg","relojes/Cartier_Santos_Steel_Blue_Dial_Diagonal_2314 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos ADLC All Black", referencia: "WSSA0048", medida: "39.8mm", material: "Acero con Correa de Caucho", caratula: "Negra", movimiento: "Automático (Cal. 1847 MC)", precio: 10040,
      imagen: "relojes/Cartier_Santos_ADLC_All_Black_Diagonal_2338.jpg",
      galeria: ["relojes/Cartier_Santos_ADLC_All_Black_Diagonal_2338 (1).jpg","relojes/Cartier_Santos_ADLC_All_Black_Diagonal_2338 (2).jpg","relojes/Cartier_Santos_ADLC_All_Black_Diagonal_2338 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Dumont Steel", referencia: "WSSA0022", medida: "38mm", material: "Acero con Correa de Piel", caratula: "Plateada", movimiento: "Manual (Cal. 430 MC)", precio: 9960,
      imagen: "relojes/Cartier_Santos_Dumont_Steel_Diagonal_2347.jpg",
      galeria: ["relojes/Cartier_Santos_Dumont_Steel_Diagonal_2347 (1).jpg","relojes/Cartier_Santos_Dumont_Steel_Diagonal_2347 (2).jpg","relojes/Cartier_Santos_Dumont_Steel_Diagonal_2347 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Pasha Steel", referencia: "WSPA0013", medida: "41mm", material: "Acero Inoxidable", caratula: "Plateada", movimiento: "Automático (Cal. 1847 MC)", precio: 10005,
      imagen: "relojes/Cartier_Pasha_Steel_Diagonal_2363.jpg",
      galeria: ["relojes/Cartier_Pasha_Steel_Diagonal_2363 (1).jpg","relojes/Cartier_Pasha_Steel_Diagonal_2363 (2).jpg","relojes/Cartier_Pasha_Steel_Diagonal_2363 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Panthère Oro Amarillo", referencia: "WGPN0009", medida: "27mm", material: "Oro Amarillo 18k", caratula: "Plateada", movimiento: "Cuarzo (Cal. 157)", precio: 10105,
      imagen: "relojes/Cartier_Panthere_Gold_Diagonal_2369.jpg",
      galeria: ["relojes/Cartier_Panthere_Gold_Diagonal_2369 (1).jpg","relojes/Cartier_Panthere_Gold_Diagonal_2369 (2).jpg","relojes/Cartier_Panthere_Gold_Diagonal_2369 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Chronograph ADLC Steel", referencia: "W2SA0010", medida: "43.3mm", material: "Acero con ADLC y Caucho", caratula: "Negra (Cronógrafo)", movimiento: "Automático Cronógrafo (Cal. 1904 CH MC)", precio: 10125,
      imagen: "relojes/Cartier_Santos_Chronograph_ADLC_Steel_Diagonal_2869.jpg",
      galeria: ["relojes/Cartier_Santos_Chronograph_ADLC_Steel_Diagonal_2869 (1).jpg","relojes/Cartier_Santos_Chronograph_ADLC_Steel_Diagonal_2869 (2).jpg","relojes/Cartier_Santos_Chronograph_ADLC_Steel_Diagonal_2869 (3).jpg"],
      status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Gold White Dial", referencia: "WGSA0009", medida: "40mm", material: "Acero Inoxidable", caratula: "Blanca", movimiento: "Automático (Cal. 1847 MC)", precio: 9995, imagen: "relojes/Cartier_Santos_Gold_White_Dial_Diagonal_32.jpeg", galeria: [], status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Skeleton Two-Tone", referencia: "W2SA0015", medida: "39.8mm", material: "Acero y Oro (Two-Tone)", caratula: "Esqueleto", movimiento: "Manual Esqueleto (Cal. 430 MC)", precio: 10070, imagen: "relojes/Cartier_Santos_Skeleton_Two-Tone_Diagonal_20.jpeg", galeria: [], status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Steel Black Dial", referencia: "WSSA0037", medida: "39.8mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático (Cal. 1847 MC)", precio: 10115, imagen: "relojes/Cartier_Santos_Steel_Black_Dial_Diagonal_34.jpeg", galeria: [], status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Steel White Dial", referencia: "WSSA0018", medida: "39.8mm", material: "Acero Inoxidable", caratula: "Blanca", movimiento: "Automático (Cal. 1847 MC)", precio: 10115, imagen: "relojes/Cartier_Santos_Steel_White_Dial_Diagonal_86.jpeg", galeria: [], status: "Disponible" },
    { marca: "Cartier", modelo: "Santos Two-Tone White Dial", referencia: "W2SA0009", medida: "39.8mm", material: "Acero y Oro", caratula: "Blanca", movimiento: "Automático (Cal. 1847 MC)", precio: 10195, imagen: "relojes/Cartier_Santos_Two-Tone_White_Dial_Diagonal_85.jpeg", galeria: [], status: "Disponible" },

    // ── DIESEL ────────────────────────────────────────────────────────────────
    { marca: "Diesel", modelo: "Mega Chief Cronógrafo Negro", referencia: "DZ4552", medida: "51mm", material: "Acero IP Negro", caratula: "Negra", movimiento: "Cuarzo Cronógrafo", precio: 10140, imagen: "relojes/Diesel_Mega_Chief_Black_Diagonal_78.jpeg", galeria: [], status: "Disponible" },

    // ── HUBLOT ────────────────────────────────────────────────────────────────
    { marca: "Hublot", modelo: "Big Bang Cerámica Negra", referencia: "301.CI.130.RX", medida: "44mm", material: "Cerámica Negra", caratula: "Negra Esqueleto", movimiento: "Automático (Cal. HUB4100)", precio: 10045, imagen: "relojes/Hublot_Big_Bang_Black_Ceramic_Diagonal_5.jpeg", galeria: [], status: "Disponible" },
    { marca: "Hublot", modelo: "Classic Fusion Skull", referencia: "525.CS.0170.LR.1104", medida: "45mm", material: "Titanio", caratula: "Calavera Esqueleto", movimiento: "Manual (Cal. HUB1710)", precio: 10035, imagen: "relojes/Hublot_Classic_Fusion_Skull_Diagonal_54.jpeg", galeria: [], status: "Disponible" },

    // ── JACOB & CO ────────────────────────────────────────────────────────────
    { marca: "Jacob & Co", modelo: "Casino Roulette", referencia: "CAS100.40.NS.UA.A", medida: "47mm", material: "Acero Inoxidable", caratula: "Ruleta Funcional", movimiento: "Manual (Complejo)", precio: 10070, imagen: "relojes/Jacob_Co_Casino_Roulette_Diagonal_62.jpeg", galeria: [], status: "Disponible" },

    // ── MONTBLANC ─────────────────────────────────────────────────────────────
    { marca: "Montblanc", modelo: "Heritage Cronógrafo", referencia: "119948", medida: "42mm", material: "Acero Inoxidable", caratula: "Plateada", movimiento: "Automático Cronógrafo (Cal. MB 25.10)", precio: 9990, imagen: "relojes/Montblanc_Chronograph_Silver_Dial_Diagonal_6.jpeg", galeria: [], status: "Disponible" },

    // ── OMEGA ─────────────────────────────────────────────────────────────────
    { marca: "Omega", modelo: "Seamaster 300M Malla Negra", referencia: "210.30.42.20.01.001", medida: "42mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático Co-Axial (Cal. 8800)", precio: 10080, imagen: "relojes/Omega_Seamaster_300M_Black_Mesh_Diagonal_7.jpeg", galeria: [], status: "Disponible" },
    { marca: "Omega", modelo: "Seamaster 300M Black Steel", referencia: "210.30.42.20.01.002", medida: "42mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático Co-Axial (Cal. 8800)", precio: 10130, imagen: "relojes/Omega_Seamaster_300M_Black_Steel_Diagonal_8.jpeg", galeria: [], status: "Disponible" },
    { marca: "Omega", modelo: "Seamaster Full Black", referencia: "210.92.44.20.01.003", medida: "44mm", material: "Titanio con Caucho", caratula: "Negra", movimiento: "Automático Co-Axial (Cal. 8912 MG)", precio: 10185, imagen: "relojes/Omega_Seamaster_Black_Black_Diagonal_10.jpeg", galeria: [], status: "Disponible" },
    { marca: "Omega", modelo: "Speedmaster Dark Side of the Moon", referencia: "311.92.44.30.01.001", medida: "44.25mm", material: "Cerámica Negra", caratula: "Negra Esqueleto", movimiento: "Manual (Cal. 1869)", precio: 10185, imagen: "relojes/Omega_Speedmaster_Dark_Side_Diagonal_18.jpeg", galeria: [], status: "Disponible" },
    { marca: "Omega", modelo: "Speedmaster Moonwatch Professional", referencia: "310.30.42.50.01.001", medida: "42mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Manual (Cal. 3861)", precio: 9955, imagen: "relojes/Omega_Speedmaster_Moonwatch_Steel_Diagonal_9.jpeg", galeria: [], status: "Disponible" },
    { marca: "Omega", modelo: "Speedmaster Snoopy Silver Snoopy Award", referencia: "310.32.42.50.02.001", medida: "42mm", material: "Acero Inoxidable", caratula: "Plateada / Azul", movimiento: "Manual (Cal. 3861)", precio: 10100, imagen: "relojes/Omega_Speedmaster_Snoopy_Diagonal_36.jpeg", galeria: [], status: "Disponible" },

    // ── PATEK PHILIPPE ────────────────────────────────────────────────────────
    { marca: "Patek Philippe", modelo: "Aquanaut 5168G Black", referencia: "5168G-010", medida: "42.2mm", material: "Oro Blanco 18k", caratula: "Negra Checkered", movimiento: "Automático (Cal. 324 SC)", precio: 10085, imagen: "relojes/Patek_Philippe_Aquanaut_Black_Diagonal_60.jpeg", galeria: [], status: "Disponible" },

    // ── ROGER DUBUIS ──────────────────────────────────────────────────────────
    { marca: "Roger Dubuis", modelo: "Excalibur Skeleton", referencia: "RDDBEX0390", medida: "42mm", material: "Titanio DLC Negra", caratula: "Esqueleto Negro", movimiento: "Manual Esqueleto (Cal. RD505SQ)", precio: 10155, imagen: "relojes/Roger_Dubuis_Excalibur_Skeleton_Diagonal_51.jpeg", galeria: [], status: "Disponible" },

    // ── ROLEX ─────────────────────────────────────────────────────────────────
    { marca: "Rolex", modelo: "Cellini Time Black Dial", referencia: "50509", medida: "39mm", material: "Oro Blanco 18k", caratula: "Negra", movimiento: "Automático (Cal. 3132)", precio: 10080, imagen: "relojes/Rolex_Cellini_Black_Dial_Diagonal_30.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Ice Blue Motif", referencia: "126234", medida: "36mm", material: "Acero Inoxidable", caratula: "Azul Hielo Motivo", movimiento: "Automático (Cal. 3235)", precio: 10040, imagen: "relojes/Rolex_Datejust_Ice_Blue_Motif_Diagonal_58.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Rhodium Roman", referencia: "126234", medida: "36mm", material: "Acero Inoxidable", caratula: "Gris Rhodium Romanos", movimiento: "Automático (Cal. 3235)", precio: 9965, imagen: "relojes/Rolex_Datejust_Rhodium_Roman_Diagonal_64.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Rhodium Roman Smooth Bezel", referencia: "126200", medida: "36mm", material: "Acero Inoxidable", caratula: "Rhodium Romanos", movimiento: "Automático (Cal. 3235)", precio: 9995, imagen: "relojes/Rolex_Datejust_Rhodium_Roman_Smooth_Bezel_Diagonal_72.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Steel Blue Dial", referencia: "126334", medida: "41mm", material: "Acero Inoxidable", caratula: "Azul", movimiento: "Automático (Cal. 3235)", precio: 9965, imagen: "relojes/Rolex_Datejust_Steel_Blue_Dial_Diagonal_23.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Steel Silver Dial", referencia: "126300", medida: "41mm", material: "Acero Inoxidable", caratula: "Plateada", movimiento: "Automático (Cal. 3235)", precio: 10200, imagen: "relojes/Rolex_Datejust_Steel_Silver_Dial_Diagonal_22.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Two-Tone Chocolate", referencia: "126333", medida: "41mm", material: "Acero y Oro Amarillo", caratula: "Chocolate", movimiento: "Automático (Cal. 3235)", precio: 10140, imagen: "relojes/Rolex_Datejust_Two-Tone_Chocolate_Diagonal_57.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Wimbledon Two-Tone", referencia: "126333", medida: "41mm", material: "Acero y Oro Amarillo", caratula: "Verde Wimbledon", movimiento: "Automático (Cal. 3235)", precio: 10195, imagen: "relojes/Rolex_Datejust_Wimbledon_Two-Tone_Diagonal_44.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Steel Green Dial", referencia: "126234", medida: "41mm", material: "Acero Inoxidable", caratula: "Verde Menta", movimiento: "Automático (Cal. 3235)", precio: 10130,
      imagen: "relojes/Rolex_Datejust_Steel_Green_Dial_Diagonal_0291.jpg",
      galeria: ["relojes/Rolex_Datejust_Steel_Green_Dial_Diagonal_0291 (1).jpg","relojes/Rolex_Datejust_Steel_Green_Dial_Diagonal_0291 (2).jpg","relojes/Rolex_Datejust_Steel_Green_Dial_Diagonal_0291 (3).jpg","relojes/Rolex_Datejust_Steel_Green_Dial_Diagonal_0291 (4).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Steel Black Dial", referencia: "126300", medida: "41mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático (Cal. 3235)", precio: 10150,
      imagen: "relojes/Rolex_Datejust_Steel_Black_Dial_Diagonal_0293.jpg",
      galeria: ["relojes/Rolex_Datejust_Steel_Black_Dial_Diagonal_0293 (1).jpg","relojes/Rolex_Datejust_Steel_Black_Dial_Diagonal_0293 (2).jpg","relojes/Rolex_Datejust_Steel_Black_Dial_Diagonal_0293 (3).jpg","relojes/Rolex_Datejust_Steel_Black_Dial_Diagonal_0293 (4).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Two-Tone Champagne", referencia: "126333", medida: "41mm", material: "Acero y Oro Amarillo", caratula: "Champaña", movimiento: "Automático (Cal. 3235)", precio: 10020,
      imagen: "relojes/Rolex_Datejust_Two-Tone_Champagne_Diagonal_1144.jpg",
      galeria: ["relojes/Rolex_Datejust_Two-Tone_Champagne_Diagonal_1144 (1).jpg","relojes/Rolex_Datejust_Two-Tone_Champagne_Diagonal_1144 (2).jpg","relojes/Rolex_Datejust_Two-Tone_Champagne_Diagonal_1144 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Lady Two-Tone White Dial", referencia: "178343", medida: "31mm", material: "Acero y Oro Amarillo", caratula: "Blanca Números Romanos", movimiento: "Automático (Cal. 2236)", precio: 10195,
      imagen: "relojes/Rolex_Datejust_Lady_Two-Tone_White_Dial_Roman_Diagonal_2855.jpg",
      galeria: ["relojes/Rolex_Datejust_Lady_Two-Tone_White_Dial_Roman_Diagonal_2855 (1).jpg","relojes/Rolex_Datejust_Lady_Two-Tone_White_Dial_Roman_Diagonal_2855 (2).jpg","relojes/Rolex_Datejust_Lady_Two-Tone_White_Dial_Roman_Diagonal_2855 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Datejust Lady Two-Tone Rose Gold", referencia: "279381RBR", medida: "31mm", material: "Acero y Oro Rosa", caratula: "Rosa Sundust Romanos", movimiento: "Automático (Cal. 2236)", precio: 10175,
      imagen: "relojes/Rolex_Datejust_Lady_Two-Tone_Rose_Gold_Smooth_Bezel_Diagonal_2865.jpg",
      galeria: ["relojes/Rolex_Datejust_Lady_Two-Tone_Rose_Gold_Smooth_Bezel_Diagonal_2865 (1).jpg","relojes/Rolex_Datejust_Lady_Two-Tone_Rose_Gold_Smooth_Bezel_Diagonal_2865 (2).jpg","relojes/Rolex_Datejust_Lady_Two-Tone_Rose_Gold_Smooth_Bezel_Diagonal_2865 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date 40 Gold Black Dial", referencia: "228238", medida: "40mm", material: "Oro Amarillo 18k", caratula: "Negra", movimiento: "Automático (Cal. 3255)", precio: 9980, imagen: "relojes/Rolex_Day-Date_Gold_Black_Dial_Diagonal_13.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Gold Black Dial", referencia: "228238", medida: "40mm", material: "Oro Amarillo 18k", caratula: "Negra Brillante", movimiento: "Automático (Cal. 3255)", precio: 9975, imagen: "relojes/Rolex_Day-Date_Gold_Black_Dial_Diagonal_81.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Gold Black Dial II", referencia: "228348RBR", medida: "40mm", material: "Oro Amarillo con Brillantes", caratula: "Negra", movimiento: "Automático (Cal. 3255)", precio: 10115, imagen: "relojes/Rolex_Day-Date_Gold_Black_Dial_Diagonal_82.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Gold Champagne", referencia: "228235", medida: "40mm", material: "Oro Rosa 18k", caratula: "Champaña", movimiento: "Automático (Cal. 3255)", precio: 10090, imagen: "relojes/Rolex_Day-Date_Gold_Champagne_Diagonal_83.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Gold Diamonds", referencia: "228348RBR", medida: "40mm", material: "Oro Amarillo con Brillantes", caratula: "Blanca con Brillantes", movimiento: "Automático (Cal. 3255)", precio: 10195, imagen: "relojes/Rolex_Day-Date_Gold_Diamonds_Diagonal_14.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Steel Black Dial", referencia: "118239", medida: "36mm", material: "Oro Blanco 18k", caratula: "Negra", movimiento: "Automático (Cal. 3155)", precio: 10105, imagen: "relojes/Rolex_Day-Date_Steel_Black_Dial_Diagonal_16.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Steel Silver Dial", referencia: "118239", medida: "36mm", material: "Oro Blanco 18k", caratula: "Plateada", movimiento: "Automático (Cal. 3155)", precio: 10175, imagen: "relojes/Rolex_Day-Date_Steel_Silver_Dial_Diagonal_17.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Day-Date Two-Tone Black Dial", referencia: "18038", medida: "36mm", material: "Acero y Oro", caratula: "Negra", movimiento: "Automático (Cal. 3055)", precio: 10165, imagen: "relojes/Rolex_Day-Date_Two-Tone_Black_Dial_Diagonal_19.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Daytona Black Dial", referencia: "116500LN", medida: "40mm", material: "Acero Inoxidable", caratula: "Negra / Bisel Cerámica", movimiento: "Automático Cronógrafo (Cal. 4130)", precio: 10195, imagen: "relojes/Rolex_Daytona_Black_Dial_Diagonal_74.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Daytona Panda", referencia: "116500LN", medida: "40mm", material: "Acero Inoxidable", caratula: "Blanca / Bisel Cerámica", movimiento: "Automático Cronógrafo (Cal. 4130)", precio: 10140, imagen: "relojes/Rolex_Daytona_Panda_Diagonal_21.jpeg", galeria: [], status: "Disponible" },

    { marca: "Rolex", modelo: "Daytona Steel White Dial", referencia: "116500LN", medida: "40mm", material: "Acero Inoxidable", caratula: "Blanca Bisel Cerámica", movimiento: "Automático Cronógrafo (Cal. 4130)", precio: 10120,
      imagen: "relojes/Rolex_Daytona_Steel_White_Dial_Diagonal_0298.jpg",
      galeria: ["relojes/Rolex_Daytona_Steel_White_Dial_Diagonal_0298 (1).jpg","relojes/Rolex_Daytona_Steel_White_Dial_Diagonal_0298 (2).jpg","relojes/Rolex_Daytona_Steel_White_Dial_Diagonal_0298 (3).jpg","relojes/Rolex_Daytona_Steel_White_Dial_Diagonal_0298 (4).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Daytona Panda Nuevo", referencia: "126500LN", medida: "40mm", material: "Acero Oystersteel", caratula: "Blanca Bisel Cerámica", movimiento: "Automático Cronógrafo (Cal. 4131)", precio: 9950,
      imagen: "relojes/Rolex_Daytona_Panda_Diagonal_0286.jpg",
      galeria: ["relojes/Rolex_Daytona_Panda_Diagonal_0286 (1).jpg","relojes/Rolex_Daytona_Panda_Diagonal_0286 (2).jpg","relojes/Rolex_Daytona_Panda_Diagonal_0286 (3).jpg","relojes/Rolex_Daytona_Panda_Diagonal_0286 (4).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Daytona Black Nuevo", referencia: "126500LN", medida: "40mm", material: "Acero Oystersteel", caratula: "Negra Bisel Cerámica", movimiento: "Automático Cronógrafo (Cal. 4131)", precio: 10095,
      imagen: "relojes/Rolex_Daytona_Black_Dial_Diagonal_0305.jpg",
      galeria: ["relojes/Rolex_Daytona_Black_Dial_Diagonal_0305 (1).jpg","relojes/Rolex_Daytona_Black_Dial_Diagonal_0305 (2).jpg","relojes/Rolex_Daytona_Black_Dial_Diagonal_0305 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Daytona Gold Turquoise Dial", referencia: "116518LN", medida: "40mm", material: "Oro Amarillo 18k y Caucho", caratula: "Turquesa", movimiento: "Automático Cronógrafo (Cal. 4130)", precio: 10200,
      imagen: "relojes/Rolex_Daytona_Gold_Turquoise_Dial_Diagonal_0813.jpg",
      galeria: ["relojes/Rolex_Daytona_Gold_Turquoise_Dial_Diagonal_0813 (2).jpg","relojes/Rolex_Daytona_Gold_Turquoise_Dial_Diagonal_0813 (3).jpg","relojes/Rolex_Daytona_Gold_Turquoise_Dial_Diagonal_0813 (4).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Explorer II Polar", referencia: "216570", medida: "42mm", material: "Acero Inoxidable", caratula: "Blanca Polar", movimiento: "Automático (Cal. 3187)", precio: 9975, imagen: "relojes/Rolex_Explorer_II_Polar_Diagonal_12.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Batman", referencia: "116710BLNR", medida: "40mm", material: "Acero Inoxidable", caratula: "Negra / Bisel Azul-Negro", movimiento: "Automático (Cal. 3186)", precio: 10010, imagen: "relojes/Rolex_GMT-Master_II_Batman_Diagonal_2.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Pepsi Jubilee", referencia: "126710BLRO", medida: "40mm", material: "Acero Oystersteel / Jubilee", caratula: "Negra / Bisel Rojo-Azul", movimiento: "Automático (Cal. 3285)", precio: 9960, imagen: "relojes/Rolex_GMT-Master_II_Pepsi_Jubilee_Diagonal_48.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Pepsi Meteorite", referencia: "126719BLRO", medida: "40mm", material: "Oro Blanco 18k", caratula: "Meteorito / Bisel Rojo-Azul", movimiento: "Automático (Cal. 3285)", precio: 10170, imagen: "relojes/Rolex_GMT-Master_II_Pepsi_Meteorite_Diagonal_45.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Pepsi Oyster", referencia: "126710BLRO", medida: "40mm", material: "Acero Oystersteel / Oyster", caratula: "Negra / Bisel Rojo-Azul", movimiento: "Automático (Cal. 3285)", precio: 10075, imagen: "relojes/Rolex_GMT-Master_II_Pepsi_Oyster_Diagonal_42.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Pepsi Oyster Nuevo", referencia: "126710BLRO", medida: "40mm", material: "Acero Oystersteel", caratula: "Negra Bisel Rojo-Azul", movimiento: "Automático (Cal. 3285)", precio: 10175,
      imagen: "relojes/Rolex_GMT-Master_II_Pepsi_Oyster_Diagonal_0310.jpg",
      galeria: ["relojes/Rolex_GMT-Master_II_Pepsi_Oyster_Diagonal_0310 (1).jpg","relojes/Rolex_GMT-Master_II_Pepsi_Oyster_Diagonal_0310 (2).jpg","relojes/Rolex_GMT-Master_II_Pepsi_Oyster_Diagonal_0310 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Root Beer", referencia: "126711CHNR", medida: "40mm", material: "Acero y Oro Everose", caratula: "Negra / Bisel Marrón-Negro", movimiento: "Automático (Cal. 3285)", precio: 10085, imagen: "relojes/Rolex_GMT-Master_II_Root_Beer_Diagonal_46.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "GMT-Master II Bruce Wayne", referencia: "126710BLNR", medida: "40mm", material: "Acero Oystersteel", caratula: "Negra Bisel Negro-Azul", movimiento: "Automático (Cal. 3285)", precio: 10050,
      imagen: "relojes/Rolex_GMT-Master_II_Bruce_Wayne_Diagonal_2220.jpg",
      galeria: ["relojes/Rolex_GMT-Master_II_Bruce_Wayne_Diagonal_2220 (1).jpg","relojes/Rolex_GMT-Master_II_Bruce_Wayne_Diagonal_2220 (2).jpg","relojes/Rolex_GMT-Master_II_Bruce_Wayne_Diagonal_2220 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Milgauss Green Glass", referencia: "116400GV", medida: "40mm", material: "Acero Inoxidable", caratula: "Negra / Vidrio Verde Z-Blue", movimiento: "Automático (Cal. 3131)", precio: 10065, imagen: "relojes/Rolex_Milgauss_Black_Dial_Green_Glass_Diagonal_1.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Sky-Dweller Steel Black Dial", referencia: "326934", medida: "42mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático (Cal. 9002)", precio: 10000, imagen: "relojes/Rolex_Sky-Dweller_Steel_Black_Dial_Diagonal_80.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Sky-Dweller Steel White Dial", referencia: "326934", medida: "42mm", material: "Acero Inoxidable", caratula: "Blanca", movimiento: "Automático (Cal. 9002)", precio: 10115,
      imagen: "relojes/Rolex_Sky-Dweller_Steel_White_Dial_Diagonal_0282.jpg",
      galeria: ["relojes/Rolex_Sky-Dweller_Steel_White_Dial_Diagonal_0282 (1).jpg","relojes/Rolex_Sky-Dweller_Steel_White_Dial_Diagonal_0282 (2).jpg","relojes/Rolex_Sky-Dweller_Steel_White_Dial_Diagonal_0282 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Sky-Dweller Steel Green Dial", referencia: "336934", medida: "42mm", material: "Acero Oystersteel", caratula: "Verde", movimiento: "Automático (Cal. 9002)", precio: 10180,
      imagen: "relojes/Rolex_Sky-Dweller_Steel_Green_Dial_Diagonal_0301.jpg",
      galeria: ["relojes/Rolex_Sky-Dweller_Steel_Green_Dial_Diagonal_0301 (1).jpg","relojes/Rolex_Sky-Dweller_Steel_Green_Dial_Diagonal_0301 (2).jpg","relojes/Rolex_Sky-Dweller_Steel_Green_Dial_Diagonal_0301 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Sky-Dweller Steel Rhodium", referencia: "336934", medida: "42mm", material: "Acero Oystersteel", caratula: "Gris Rhodium", movimiento: "Automático (Cal. 9002)", precio: 10100,
      imagen: "relojes/Rolex_Sky-Dweller_Steel_Rhodium_Diagonal_1370.jpg",
      galeria: ["relojes/Rolex_Sky-Dweller_Steel_Rhodium_Diagonal_1370 (1).jpg","relojes/Rolex_Sky-Dweller_Steel_Rhodium_Diagonal_1370 (2).jpg","relojes/Rolex_Sky-Dweller_Steel_Rhodium_Diagonal_1370 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Black Jubilee", referencia: "126610LN", medida: "41mm", material: "Acero Oystersteel / Jubilee", caratula: "Negra / Bisel Cerámica", movimiento: "Automático (Cal. 3235)", precio: 10020, imagen: "relojes/Rolex_Submariner_Black_Jubilee_Diagonal_66.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Black Oyster", referencia: "126610LN", medida: "41mm", material: "Acero Oystersteel / Oyster", caratula: "Negra / Bisel Cerámica", movimiento: "Automático (Cal. 3235)", precio: 9970, imagen: "relojes/Rolex_Submariner_Black_Oyster_Diagonal_70.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Date Bluesy", referencia: "126613LB", medida: "41mm", material: "Acero y Oro Amarillo", caratula: "Azul / Bisel Cerámica Azul", movimiento: "Automático (Cal. 3235)", precio: 10140, imagen: "relojes/Rolex_Submariner_Bluesy_Diagonal_39.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Date Cookie Monster", referencia: "126619LB", medida: "41mm", material: "Oro Blanco 18k", caratula: "Azul / Bisel Cerámica Azul", movimiento: "Automático (Cal. 3235)", precio: 9960, imagen: "relojes/Rolex_Submariner_Cookie_Monster_Diagonal_15.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Gold Black", referencia: "126618LN", medida: "41mm", material: "Oro Amarillo 18k", caratula: "Negra / Bisel Cerámica", movimiento: "Automático (Cal. 3235)", precio: 10015, imagen: "relojes/Rolex_Submariner_Gold_Black_Diagonal_84.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Date Gold Blue", referencia: "126618LB", medida: "41mm", material: "Oro Amarillo 18k", caratula: "Azul / Bisel Cerámica Azul", movimiento: "Automático (Cal. 3235)", precio: 10095, imagen: "relojes/Rolex_Submariner_Gold_Blue_Diagonal_49.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Hulk Green", referencia: "116610LV", medida: "40mm", material: "Acero Inoxidable", caratula: "Verde / Bisel Cerámica Verde", movimiento: "Automático (Cal. 3135)", precio: 10135, imagen: "relojes/Rolex_Submariner_Hulk_Diagonal_40.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Hulk Jubilee", referencia: "126610LV", medida: "41mm", material: "Acero Oystersteel / Jubilee", caratula: "Verde / Bisel Cerámica Verde", movimiento: "Automático (Cal. 3235)", precio: 9965, imagen: "relojes/Rolex_Submariner_Hulk_Jubilee_Diagonal_71.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner No-Date", referencia: "124060", medida: "41mm", material: "Acero Oystersteel", caratula: "Negra Bisel Cerámica", movimiento: "Automático (Cal. 3230)", precio: 9970,
      imagen: "relojes/Rolex_Submariner_No-Date_Diagonal_2137.jpg",
      galeria: ["relojes/Rolex_Submariner_No-Date_Diagonal_2137 (1).jpg","relojes/Rolex_Submariner_No-Date_Diagonal_2137 (2).jpg","relojes/Rolex_Submariner_No-Date_Diagonal_2137 (3).jpg","relojes/Rolex_Submariner_No-Date_Diagonal_2137 (4).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Date Smurf", referencia: "126619LB", medida: "41mm", material: "Oro Blanco 18k", caratula: "Azul / Bisel Cerámica Azul", movimiento: "Automático (Cal. 3235)", precio: 9990, imagen: "relojes/Rolex_Submariner_Smurf_Diagonal_47.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Submariner Two-Tone Black", referencia: "126613LN", medida: "41mm", material: "Acero y Oro Amarillo", caratula: "Negra / Bisel Cerámica", movimiento: "Automático (Cal. 3235)", precio: 9985, imagen: "relojes/Rolex_Submariner_Two-Tone_Black_Diagonal_43.jpeg", galeria: [], status: "Disponible" },
    { marca: "Rolex", modelo: "Oyster Perpetual Candy Pink", referencia: "124200", medida: "36mm", material: "Acero Oystersteel", caratula: "Rosa Candy", movimiento: "Automático (Cal. 3230)", precio: 10125,
      imagen: "relojes/Rolex_Oyster_Perpetual_Candy_Pink_Diagonal_0312.jpg",
      galeria: ["relojes/Rolex_Oyster_Perpetual_Candy_Pink_Diagonal_0312 (1).jpg","relojes/Rolex_Oyster_Perpetual_Candy_Pink_Diagonal_0312 (2).jpg","relojes/Rolex_Oyster_Perpetual_Candy_Pink_Diagonal_0312 (3).jpg"],
      status: "Disponible" },
    { marca: "Rolex", modelo: "Yacht-Master Rose Gold Oysterflex", referencia: "268655", medida: "37mm", material: "Oro Everose 18k", caratula: "Plateada Rhodium", movimiento: "Automático (Cal. 2236)", precio: 9975, imagen: "relojes/Rolex_Yacht-Master_Rose_Gold_Oysterflex_Diagonal_31.jpeg", galeria: [], status: "Disponible" },

    // ── TAG HEUER ─────────────────────────────────────────────────────────────
    { marca: "Tag Heuer", modelo: "Aquaracer Professional 300 Blue", referencia: "WBP2011.BA0618", medida: "43mm", material: "Acero Inoxidable", caratula: "Azul", movimiento: "Automático (Cal. 5)", precio: 10055, imagen: "relojes/Tag_Heuer_Aquaracer_Blue_Diagonal_63.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Carrera Cronógrafo Black Leather", referencia: "CV2014.FC6233", medida: "41mm", material: "Acero / Piel", caratula: "Negra", movimiento: "Automático Cronógrafo (Cal. 16)", precio: 9980, imagen: "relojes/Tag_Heuer_Carrera_Chronograph_Black_Leather_Diagonal_4.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Carrera Heuer 01 Black Metal", referencia: "CAR201Z.FT6046", medida: "45mm", material: "Titanio y Caucho", caratula: "Negra / Esqueleto", movimiento: "Automático Cronógrafo (Cal. Heuer 01)", precio: 10135, imagen: "relojes/Tag_Heuer_Carrera_Heuer_01_Black_Metal_Diagonal_3.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Carrera Heuer 01 Blue", referencia: "CAR201T.FT6046", medida: "45mm", material: "Titanio y Caucho", caratula: "Azul / Esqueleto", movimiento: "Automático Cronógrafo (Cal. Heuer 01)", precio: 10035, imagen: "relojes/Tag_Heuer_Carrera_Heuer_01_Blue_Diagonal_41.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Carrera Heuer 01 Rubber", referencia: "CAR201Z.FT6046", medida: "45mm", material: "Acero y Caucho", caratula: "Negra / Esqueleto", movimiento: "Automático Cronógrafo (Cal. Heuer 01)", precio: 10105, imagen: "relojes/Tag_Heuer_Carrera_Heuer_01_Rubber_Diagonal_11.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Carrera Cronógrafo Black Metal", referencia: "CBS2190.BA0641", medida: "44mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático Cronógrafo (Cal. Heuer 02)", precio: 9990, imagen: "relojes/Tag_Heuer_Carrera_Chrono_Black_Metal_Diagonal_87.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Formula 1 Cronógrafo Black", referencia: "CAZ1010.BA0842", medida: "43mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Cuarzo Cronógrafo (Cal. 7)", precio: 9970, imagen: "relojes/Tag_Heuer_Formula_1_Chrono_Black_Diagonal_38.jpeg", galeria: [], status: "Disponible" },
    { marca: "Tag Heuer", modelo: "Formula 1 Cronógrafo Blue", referencia: "CAZ1014.BA0842", medida: "43mm", material: "Acero Inoxidable", caratula: "Azul", movimiento: "Cuarzo Cronógrafo (Cal. 7)", precio: 10015, imagen: "relojes/Tag_Heuer_Formula_1_Chrono_Blue_Diagonal_28.jpeg", galeria: [], status: "Disponible" },

    { marca: "Tag Heuer", modelo: "Monaco Gulf Edition", referencia: "CAW211R.FC6401", medida: "39mm", material: "Acero Inoxidable", caratula: "Azul / Naranja", movimiento: "Automático Cronógrafo (Cal. Heuer 02)", precio: 10005, imagen: "relojes/Tag_Heuer_Monaco_Gulf_Diagonal_35.jpeg", galeria: [], status: "Disponible" },

    // ── VACHERON CONSTANTIN ───────────────────────────────────────────────────
    { marca: "Vacheron Constantin", modelo: "Overseas Cronógrafo Black", referencia: "5500V/110A-B148", medida: "42.5mm", material: "Acero Inoxidable", caratula: "Negra", movimiento: "Automático Cronógrafo (Cal. 5200)", precio: 10175, imagen: "relojes/Vacheron_Constantin_Overseas_Black_Diagonal_24.jpeg", galeria: [], status: "Disponible" },
];
